FROM node:${NODE_VERSION}-alpine

RUN apk add --no-cache curl bash && \
    curl -1sLf 'https://dl.cloudsmith.io/public/infisical/infisical-cli/setup.alpine.sh' | bash && \
    apk add --no-cache infisical

WORKDIR /app

# Copy application files
COPY . .

# Build the application
RUN ${BUILD_CMD}

# Expose port 3000 (internal container port)
EXPOSE 3000

# Start the application
CMD ${SERVE_CMD}
